name: "erorr"
description: "오타 또는 잘못된 설명이 있습니다 🐛"
labels: 에러
body:

  - type: textarea
    attributes:
      label: 설명
      description: |
        에러가 난 부분 또는 URL을 주세요.
      placeholder: |
        여기가 잘못된 것 같아요.
  - type: textarea
    attributes:
      label: 추가사항
      description: |
        더 문제가 있을까요?

