name: "Erorr"
description: "There is a problem with your code 😅"
labels: error
body:

  - type: textarea
    attributes:
      label: explanation
      description: |
        Where do you think the error is coming from?
      placeholder: |
        I think there is an error in the XCamare part
  - type: textarea
    attributes:
      label: More details
      description: |
        Any more problems?

