name: "패턴 설명"
description: "이것도 설명해주세요 🙏"
body:

  - type: textarea
    attributes:
      label: 이것도 설명해주시면 좋겠습니다!
      description: |
        [Explain] 원하느 디자인 패턴을 알려주세요!! 😏
      placeholder: |
        VIP 패턴을 설명해주셨으면 좋겠습니다.
  - type: textarea
    attributes:
      label: 추가사항
      description: |
        [추가사항] 예제 코드도 주셨으면 좋겠습니다.  
